site_name: Inquirer Textual Documentation
repo_url: https://github.com/robvanderleek/inquirer-textual
theme:
  name: material
  palette:
  - scheme: slate
    primary: teal
    toggle:
      icon: material/lightbulb
      name: Switch to light mode
  - scheme: default
    primary: teal
    toggle:
      icon: material/lightbulb-outline
      name: Switch to dark mode
  logo: assets/logo-light.png
  favicon: assets/favicon.ico
  features:
    - toc.integrate
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.footer
    - content.code.copy
plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
  - glightbox:
      draggable: false
      background: none
      shadow: false
  - search
markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - Inquirer Textual: 'index.md'
  - Getting Started: 'getting-started/index.md'
  - Examples:
    - Prompts:
      - Checkbox: 'examples/prompts/checkbox.md'
      - Confirm: 'examples/prompts/confirm.md'
      - Editor: 'examples/prompts/editor.md'
      - External: 'examples/prompts/external.md'
      - Multi: 'examples/prompts/multi.md'
      - Number: 'examples/prompts/number.md'
      - Path: 'examples/prompts/path.md'
      - Pattern: 'examples/prompts/pattern.md'
      - Secret: 'examples/prompts/secret.md'
      - Select: 'examples/prompts/select.md'
      - Text: 'examples/prompts/text.md'
    - Apps:
      - App: 'examples/apps/app.md'
  - CLI: 'cli/index.md'
  - Themes: 'themes/index.md'
  - Reference:
    - Checkbox: 'reference/checkbox.md'
    - Confirm: 'reference/confirm.md'
    - Editor: 'reference/editor.md'
    - Multi: 'reference/multi.md'
    - Number: 'reference/number.md'
    - Path: 'reference/path.md'
    - Pattern: 'reference/pattern.md'
    - Secret: 'reference/secret.md'
    - Select: 'reference/select.md'
    - Text: 'reference/text.md'
  - FAQ: 'faq.md'
